installType: ocp
rbacApiVersion: rbac.authorization.k8s.io
namespace: openshift-operator-lifecycle-manager
catalog_namespace: openshift-marketplace
operator_namespace: openshift-operators
imagestream: true
writeStatusName: operator-lifecycle-manager
writeStatusNameCatalog: operator-lifecycle-manager-catalog
writePackageServerStatusName: operator-lifecycle-manager-packageserver
olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607
    pullPolicy: IfNotPresent
  service:
    internalPort: 8443
    externalPort: 8443
  clientCASecret: olm-operator-serving-cert
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 120
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 120
  tlsSecret: olm-operator-serving-cert
  resources:
    requests:
      cpu: 10m
      memory: 160Mi
catalog:
  replicaCount: 1
  opmImageArgs: -opmImage=quay.io/operator-framework/configmap-operator-registry:latest
  image:
    ref: quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607
    pullPolicy: IfNotPresent
  service:
    internalPort: 8443
    externalPort: 8443
  clientCASecret: catalog-operator-serving-cert
  tlsSecret: catalog-operator-serving-cert
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 120
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 120
  resources:
    requests:
      cpu: 10m
      memory: 80Mi
package:
  replicaCount: 2
  maxUnavailable: 1
  maxSurge: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607
    pullPolicy: IfNotPresent
  service:
    internalPort: 5443
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 120
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 120
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
monitoring:
  enabled: true
  namespace: openshift-monitoring
